import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ChevronRight, Eye, Fingerprint, LockKeyhole, Volume2, VolumeX } from 'lucide-react';

type Gender = 'male' | 'female';
type FunctionKey = 'Se'|'Si'|'Ne'|'Ni'|'Te'|'Ti'|'Fe'|'Fi';
type Stage = 'boot'|'register'|'assessment'|'reveal'|'dossier';
type Option = {text:string,fn:FunctionKey,echo?:string};
type Question = {code:string,domain?:string,scene:string,a:Option,b:Option};

const asset=(path:string)=>`${import.meta.env.BASE_URL}${path}`;
const stacks:Record<string,FunctionKey[]>={ISTJ:['Si','Te','Fi','Ne'],ISFJ:['Si','Fe','Ti','Ne'],INFJ:['Ni','Fe','Ti','Se'],INTJ:['Ni','Te','Fi','Se'],ISTP:['Ti','Se','Ni','Fe'],ISFP:['Fi','Se','Ni','Te'],INFP:['Fi','Ne','Si','Te'],INTP:['Ti','Ne','Si','Fe'],ESTP:['Se','Ti','Fe','Ni'],ESFP:['Se','Fi','Te','Ni'],ENFP:['Ne','Fi','Te','Si'],ENTP:['Ne','Ti','Fe','Si'],ESTJ:['Te','Si','Ne','Fi'],ESFJ:['Fe','Si','Ne','Ti'],ENFJ:['Fe','Ni','Se','Ti'],ENTJ:['Te','Ni','Se','Fi']};
const aliases:Record<string,string>={INTJ:'社会达尔文屠夫',INTP:'无底线观测者',ENTJ:'马基雅维利暴君',ENTP:'虚无主义煽动家',INFJ:'精神邪教主',INFP:'受害者暴君',ENFJ:'认知寄生母体',ENFP:'狂热毒源体',ISTJ:'极权执行官',ISFJ:'窒息施恩者',ESTJ:'齿轮独裁者',ESFJ:'蜂巢审判长',ISTP:'冰冷解剖者',ISFP:'绝望美学家',ESTP:'掠食资本家',ESFP:'痛觉狂欢客'};
const questions:Question[]=[
{code:'P-01',scene:'陌生房间里只留下了一分钟。你首先会记住什么？',a:{text:'眼前物品的位置、声音与可以立刻利用的出口',fn:'Se'},b:{text:'它与我经历过的某个地方有哪些细节重合',fn:'Si'}},
{code:'P-02',scene:'一份缺失了三页的案件记录摆在面前。',a:{text:'同时列出数种可能，寻找意外连接',fn:'Ne'},b:{text:'压缩所有线索，寻找唯一贯穿始终的意图',fn:'Ni'}},
{code:'J-01',scene:'团队必须在今晚决定牺牲哪一个方案。',a:{text:'比较成本、速度和可以被验证的实际成果',fn:'Te'},b:{text:'先检查规则本身是否自洽，再接受结论',fn:'Ti'}},
{code:'J-02',scene:'一个人承认犯错，却拒绝解释原因。',a:{text:'观察这件事如何影响所有人的关系与情绪',fn:'Fe'},b:{text:'判断他的行为是否背叛了自己真正相信的东西',fn:'Fi'}},
{code:'P-03',scene:'监控画面只出现了半秒钟的异常。',a:{text:'相信当时直接看到的动作与物理变化',fn:'Se'},b:{text:'回查此前每一次相似记录，寻找稳定偏差',fn:'Si'}},
{code:'P-04',scene:'两名证人给出了完全相反的说法。',a:{text:'保留矛盾，让更多解释同时存在',fn:'Ne'},b:{text:'寻找他们都没有说出口的共同前提',fn:'Ni'}},
{code:'J-03',scene:'制度没有禁止一件明显会伤害人的事。',a:{text:'立即补上可执行的流程与责任人',fn:'Te'},b:{text:'先定义问题，避免用错误规则制造新漏洞',fn:'Ti'}},
{code:'J-04',scene:'公开真相会让无辜者承受长期羞辱。',a:{text:'先考虑群体将如何反应以及如何降低伤害',fn:'Fe'},b:{text:'即使不被理解，也不违背个人的道德底线',fn:'Fi'}},
{code:'S-01',scene:'压力下，你发现计划正在失控。',a:{text:'进入现场，边行动边修正判断',fn:'Se'},b:{text:'回到已验证的方法，一项项恢复秩序',fn:'Si'}},
{code:'S-02',scene:'有人暗示你正在参与一项更大的计划。',a:{text:'追踪每一种可能扩散出去的后果',fn:'Ne'},b:{text:'直觉上锁定那个最可能的最终目的',fn:'Ni'}},
{code:'S-03',scene:'所有人都等待你承担责任。',a:{text:'接管资源并给出明确指令',fn:'Te'},b:{text:'拒绝仓促表态，独自重算所有因果',fn:'Ti'}},
{code:'S-04',scene:'一个重要的人请求你隐瞒他的过错。',a:{text:'衡量关系、信任和其他人的承受能力',fn:'Fe'},b:{text:'先问自己是否愿意成为这种行为的一部分',fn:'Fi'}},
{code:'R-01',domain:'跨情境复核',scene:'学习一项需要精确操作的新技能时，哪种方式通常更有效？',a:{text:'尽早实际操作，通过实时感官反馈掌握动作',fn:'Se'},b:{text:'先形成稳定步骤，并用既有参照校准误差',fn:'Si'}},
{code:'R-02',domain:'跨情境复核',scene:'阅读一组彼此松散的新材料时，你更常获得哪种理解？',a:{text:'材料不断触发新联想，使问题边界向外扩展',fn:'Ne'},b:{text:'零散内容逐渐汇成一个方向明确的核心印象',fn:'Ni'}},
{code:'R-03',domain:'跨情境复核',scene:'判断一项复杂结论是否可靠时，你更看重哪种证据？',a:{text:'它能否产生稳定、可测量且可复核的外部结果',fn:'Te'},b:{text:'它是否来自定义清晰、前提充分且无矛盾的推导',fn:'Ti'}},
{code:'R-04',domain:'跨情境复核',scene:'表达一项可能不受欢迎的立场时，你更自然的做法是？',a:{text:'调整表达，使群体仍可能理解并维持合作',fn:'Fe'},b:{text:'保持表达与真实信念一致，即使承受关系压力',fn:'Fi'}},
{code:'V-01',domain:'观察者效应',scene:'回看一段记录自己的无声影像时，你发现画面中的自己比现实慢了一秒。你会先依据什么判断？',a:{text:'逐帧核对动作、光线与设备延迟，确认可观察偏差',fn:'Se'},b:{text:'与过去见过的影像故障比较，寻找重复特征',fn:'Si'}},
{code:'V-02',domain:'身份连续性',scene:'档案中出现一份署有你名字、但你确信从未填写的问卷。',a:{text:'保留身份误用、记忆错误与系统生成等多种解释',fn:'Ne'},b:{text:'追踪所有细节最终共同指向的那个单一目的',fn:'Ni'}},
{code:'V-03',domain:'控制条件',scene:'系统要求你删除一名参与者的数据，否则全部实验记录将被公开。',a:{text:'评估可验证后果，选择总体损失最低的执行方案',fn:'Te'},b:{text:'检查二选一前提是否成立，并寻找逻辑上的第三路径',fn:'Ti'}},
{code:'V-04',domain:'伦理复核',scene:'屏幕提示：与你同时作答的另一人，能看见你的全部选择。',a:{text:'优先评估信息暴露将如何改变双方关系与群体反应',fn:'Fe'},b:{text:'仍按自己认可的价值边界作答，不因被观察而修饰',fn:'Fi'}}];

const echoes=[
'记录中出现了你尚未作出的选择。','音轨中多出一次呼吸。','系统已将犹豫时间写入另一份档案。','该选项曾由 17 名已注销观察者选择。',
'指针轨迹显示你短暂停在一个不存在的选项上。','答案已在 00:00:16 前提交。','复核员编号与受试者编号相同。','屏幕外有人轻声重复了你的答案。'
];
const intrusions:Record<number,string>={2:'我不记得自己同意过这一题。',5:'以上描述的证人是我。',9:'选择记录里为什么已经有我的答案？',13:'这不是刚才出现过的题目。',16:'画面中的人比我先做出了选择。',18:'删除观察者，而不是参与者。'};
const sideSignals:Record<number,string>={1:'SESSION 02 CONNECTED',4:'请不要转头',7:'BREATH / 02',10:'左侧没有人',12:'你撤回过这道题',15:'SUBJECT IS READING',17:'不要选择第五项',19:'观察者位置已确认'};

export default function Home(){
const previewParams=new URLSearchParams(window.location.search);const requestedType=(previewParams.get('result')||'').toUpperCase();const directType=Object.hasOwn(stacks,requestedType)?requestedType:'';const requestedGender=previewParams.get('gender');
const[stage,setStage]=useState<Stage>(directType?'reveal':'boot');const[gender,setGender]=useState<Gender>(requestedGender==='male'?'male':'female');const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<FunctionKey[]>([]);const[weights,setWeights]=useState<number[]>([]);const[intrusionCount,setIntrusionCount]=useState(0);const[muted,setMuted]=useState(false);const[noticed,setNoticed]=useState(directType?1:0);const[echo,setEcho]=useState('');const[locked,setLocked]=useState(false);const[consent,setConsent]=useState(false);const[anomalyKind,setAnomalyKind]=useState('');const card=useRef<HTMLDivElement>(null);
const sound=useRef<{ctx:AudioContext,master:GainNode}|null>(null);
useEffect(()=>{document.title='观察者登记｜16'},[]);
useEffect(()=>{document.body.dataset.signal=stage==='assessment'&&sideSignals[index]?String(index):'';return()=>{delete document.body.dataset.signal}},[stage,index]);
useEffect(()=>()=>{void sound.current?.ctx.close()},[]);
const startSound=()=>{if(sound.current){void sound.current.ctx.resume();return}const ctx=new AudioContext();const master=ctx.createGain();const limiter=ctx.createDynamicsCompressor();master.gain.setValueAtTime(0,ctx.currentTime);master.gain.linearRampToValueAtTime(.48,ctx.currentTime+2.8);limiter.threshold.value=-22;limiter.knee.value=18;limiter.ratio.value=7;limiter.attack.value=.08;limiter.release.value=.7;master.connect(limiter).connect(ctx.destination);const drone=ctx.createGain();drone.gain.value=.032;drone.connect(master);[43.2,57.7,86.4].forEach((hz,i)=>{const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=i===2?'triangle':'sine';osc.frequency.value=hz;osc.detune.value=[-4,3,-7][i];gain.gain.value=[.5,.28,.1][i];osc.connect(gain).connect(drone);osc.start()});const lfo=ctx.createOscillator();const lfoGain=ctx.createGain();lfo.frequency.value=.061;lfoGain.gain.value=.009;lfo.connect(lfoGain).connect(drone.gain);lfo.start();const electronics=ctx.createGain();const terminalFilter=ctx.createBiquadFilter();electronics.gain.value=.0055;terminalFilter.type='lowpass';terminalFilter.frequency.value=720;terminalFilter.Q.value=1.1;electronics.connect(terminalFilter).connect(master);[216,323.6].forEach((hz,i)=>{const carrier=ctx.createOscillator();const voice=ctx.createGain();carrier.type=i?'sine':'triangle';carrier.frequency.value=hz;carrier.detune.value=i?7:-5;voice.gain.value=i?.22:.48;carrier.connect(voice).connect(electronics);carrier.start()});const pulse=ctx.createOscillator();const pulseDepth=ctx.createGain();pulse.type='square';pulse.frequency.value=.187;pulseDepth.gain.value=.0032;pulse.connect(pulseDepth).connect(electronics.gain);pulse.start();const scan=ctx.createOscillator();const scanDepth=ctx.createGain();scan.frequency.value=.027;scanDepth.gain.value=34;scan.connect(scanDepth).connect(terminalFilter.frequency);scan.start();const noise=ctx.createBufferSource();const buffer=ctx.createBuffer(1,ctx.sampleRate*5,ctx.sampleRate);const data=buffer.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){brown=(brown+(Math.random()*2-1)*.035)/1.035;data[i]=brown*.8}noise.buffer=buffer;noise.loop=true;const high=ctx.createBiquadFilter();const low=ctx.createBiquadFilter();const noiseGain=ctx.createGain();high.type='highpass';high.frequency.value=32;low.type='lowpass';low.frequency.value=360;low.Q.value=.55;noiseGain.gain.value=.026;noise.connect(high).connect(low).connect(noiseGain).connect(master);noise.start();sound.current={ctx,master}};
const toggleSound=()=>{if(!sound.current){startSound();setMuted(false);return}const next=!muted;setMuted(next);sound.current.master.gain.cancelScheduledValues(sound.current.ctx.currentTime);sound.current.master.gain.setTargetAtTime(next?0:.48,sound.current.ctx.currentTime,.18)};
const scores=useMemo(()=>{const s={} as Record<FunctionKey,number>;(['Se','Si','Ne','Ni','Te','Ti','Fe','Fi'] as FunctionKey[]).forEach(k=>s[k]=0);answers.forEach(k=>s[k]++);return s},[answers]);
const matches=useMemo(()=>Object.entries(stacks).map(([name,stack])=>({name,value:stack.reduce((sum,fn,i)=>sum+scores[fn]*[4,3,2,1][i],0)})).sort((a,b)=>b.value-a.value),[scores]);
const type=directType||matches[0]?.name||'INTJ';
const stack=stacks[type];
const confidence=Math.max(52,Math.min(94,Math.round(58+(matches[0]?.value-(matches[1]?.value||0))*4)));
const choose=(option:Option,side:0|1,weight:1|2)=>{if(locked)return;setLocked(true);setAnomalyKind(['drift','rewind','double','presence'][(index+side+weight)%4]);setEcho(option.echo||echoes[(index*2+side)%echoes.length]);const next=[...answers,...Array(weight).fill(option.fn)];setTimeout(()=>{setAnswers(next);setWeights([...weights,weight]);setEcho('');setAnomalyKind('');setLocked(false);if(index===questions.length-1){setStage('reveal');setTimeout(()=>setNoticed(1),1800)}else setIndex(index+1)},760)};
const chooseIntrusion=()=>{if(locked)return;setLocked(true);setIntrusionCount(v=>v+1);setAnomalyKind('presence');setEcho('该反应不属于量表。系统仍将其记为有效。');setTimeout(()=>{setEcho('');setAnomalyKind('');setLocked(false);if(index===questions.length-1){setStage('reveal');setTimeout(()=>setNoticed(1),1800)}else setIndex(index+1)},1100)};
const moveEyes=(clientX:number,clientY:number)=>{if(!card.current||stage!=='reveal')return;const r=card.current.getBoundingClientRect();const dx=Math.max(-1,Math.min(1,(clientX-(r.left+r.width/2))/(r.width/2)));const dy=Math.max(-1,Math.min(1,(clientY-(r.top+r.height*.42))/(r.height/2)));card.current.style.setProperty('--tilt-y',`${dx*4.5}deg`);card.current.style.setProperty('--tilt-x',`${dy*-3.5}deg`);card.current.style.setProperty('--shift-x',`${dx*-7}px`);card.current.style.setProperty('--shift-y',`${dy*-5}px`);if(noticed===1&&(Math.abs(dx)>.2||Math.abs(dy)>.2))setNoticed(2)};
const portrait=asset(`portraits/${type.toLowerCase()}-${gender}.png`);
return <main className={`shell stage-${stage} anomaly-${anomalyKind}`} onPointerMove={e=>moveEyes(e.clientX,e.clientY)} onPointerDown={e=>moveEyes(e.clientX,e.clientY)}><div className="grain"/><div className="watcher-mark">+</div><header><div className="wordmark"><Fingerprint size={18}/><span>PRISM / XVI</span></div><div className="sys-state"><i/> INTERNAL NETWORK</div><button className="sound" onClick={toggleSound} aria-label={muted?'打开声音':'静音'}>{muted?<VolumeX/>:<Volume2/>}</button></header>
{stage==='boot'&&<section className="boot declaration enter"><div className="document-head"><span>PRISM 人格研究与信息评估中心</span><b>受试者知情告知书</b><em>文件编号：PR-XVI/BA-020　密级：内部</em></div><div className="legal-copy"><p>本项目采用结构化情境判断任务，对信息获取与决策偏好进行研究性评估。系统将记录选项、停留时间、撤回行为及终端交互轨迹，用于生成认知功能序列匹配结果。</p><p>评估结果仅描述相对偏好，不用于医学诊断、精神病理判定、就业筛选或现实犯罪风险评估。参与者可随时终止，但已生成的观察编号可能继续存在于本地会话中。</p><div className="protocol"><span>测量框架</span><b>8 COGNITIVE PROCESSES</b><span>任务形式</span><b>20 × 4-LEVEL + VALIDITY ITEMS</b><span>档案状态</span><b>UNRESOLVED</b></div></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>本人已阅读并理解以上说明，自愿进入评估程序。</span></label><button disabled={!consent} className="action" onClick={()=>{startSound();setStage('register')}}><LockKeyhole size={17}/> 签署并申请临时阅档权限</button><div className="seal">PRISM<br/>XVI</div><small>PRISM 为本互动作品中的虚构研究机构；本页面并非任何官方 MBTI® 测评或医疗服务。</small></section>}
{stage==='register'&&<section className="register enter"><button className="back" onClick={()=>setStage('boot')}><ArrowLeft/> 返回</button><div className="terminal-label">OPERATOR REGISTRATION</div><p className="prompt">选择系统用于匹配镜像样本的外观档案。</p><div className="gender-pick"><button className={gender==='female'?'active':''} onClick={()=>setGender('female')}><img src={asset('mbti-women.jpg')} alt="女性样本总表"/><span>女性镜像样本</span></button><button className={gender==='male'?'active':''} onClick={()=>setGender('male')}><img src={asset('mbti-men.jpg')} alt="男性样本总表"/><span>男性镜像样本</span></button></div><div className="notice"><b>研究性情境量表 · 20 项</b><p>依据荣格类型动力学的公开定义，以四组认知过程、重复测量、跨情境复核与观察者效应项目估计功能序列。题目为原创编写，不复制官方 MBTI® 题库。</p><details><summary>方法与适用边界</summary><p>本工具比较八种认知过程的相对偏好。非标准选项只计入反应有效性异常，不参与人格功能计分。结果用于叙事体验，不构成心理、临床或犯罪风险诊断。</p></details></div><button className="action" onClick={()=>setStage('assessment')}>开始登记 <ChevronRight/></button></section>}
{stage==='assessment'&&<section className={`assessment enter ${echo?'anomaly':''}`} key={index}><div className="question-top"><button disabled={locked} className="back" onClick={()=>index?(setIndex(index-1),setAnswers(answers.slice(0,-1))):setStage('register')}><ArrowLeft/> 撤回</button><span>{String(index+1).padStart(2,'0')} / {questions.length}</span></div><div className="meter"><i style={{width:`${((index+1)/questions.length)*100}%`}}/></div><div className="terminal-label">ITEM {questions[index].code}{questions[index].domain&&` · ${questions[index].domain}`}</div><h1>{questions[index].scene}</h1><div className="answers scale"><button disabled={locked} onClick={()=>choose(questions[index].a,0,2)}><b>01</b><span><strong>非常接近</strong>{questions[index].a.text}</span></button><button disabled={locked} onClick={()=>choose(questions[index].a,0,1)}><b>02</b><span><strong>较为接近</strong>{questions[index].a.text}</span></button><button disabled={locked} onClick={()=>choose(questions[index].b,1,1)}><b>03</b><span><strong>较为接近</strong>{questions[index].b.text}</span></button><button disabled={locked} onClick={()=>choose(questions[index].b,1,2)}><b>04</b><span><strong>非常接近</strong>{questions[index].b.text}</span></button>{intrusions[index]&&<button className="intrusion-option" disabled={locked} onClick={chooseIntrusion}><b>—</b><span>{intrusions[index]}</span></button>}</div><div className={`answer-echo ${echo?'visible':''}`} aria-live="polite"><span>{intrusionCount?'VALIDITY DEVIATION':'RESPONSE ANOMALY'}</span>{echo}</div><p className="footnote">请选择更接近你长期、自然倾向的一项，而非理想中的自己。</p></section>}
{stage==='reveal'&&<section className="reveal enter"><div className="match-line">FUNCTION SEQUENCE MATCHED · {confidence}%</div><p className="your-type">您的人格是：</p><div className="photo-space" style={{backgroundImage:`url(${portrait})`}}><div className={`live-card ${noticed?'awakened':''}`} ref={card}><img className="depth-back" src={portrait} alt={`${type} 单人证件照`}/><div className="depth-mid"><img src={portrait} alt=""/></div><div className="depth-subject"><img src={portrait} alt=""/><div className="eye left" style={{backgroundImage:`url(${portrait})`}}/><div className="eye right" style={{backgroundImage:`url(${portrait})`}}/></div><div className="face-light"/><div className="screen-lines"/><div className="id-strip"><span>SUBJECT XVI-{type}</span><b>{type}</b><em>{aliases[type]}</em></div></div></div><div className="function-stack">{stack.map((fn,i)=><span key={fn}><small>{['主导','辅助','第三','劣势'][i]}</small>{fn}</span>)}</div><p className="result-note">功能序列匹配度 {confidence}% · 次近候选 {matches[1]?.name}。该结果描述偏好，不代表能力、品格或临床结论。</p><div className={`system-alert level-${noticed}`}>{noticed===0?'正在重建影像纵深…':noticed===1?'空间图层已分离。请移动指针确认。':'前景人物与背景的距离正在增加。'}</div>{noticed===2&&<button className="action danger" onClick={()=>setStage('dossier')}>打开受限档案 <ChevronRight/></button>}</section>}
{stage==='dossier'&&<section className="dossier enter"><div className="access-row"><span>ACCESS LEVEL 01</span><b>已解锁 1 / 32</b></div><div className="redaction"><span>内部复核通知</span><p>系统在十一年前已将该受试者标记为死亡。</p><p>当前照片的视觉反馈并非来自原始影像文件。</p><strong>请确认：你是否仍要继续观察？</strong></div><div className="evidence-file"><div><small>异常记录</small><b>LIVE DOSSIER / 00:16:33</b></div><p>在你移动指针前，系统已经提前生成了受试者下一次注视的位置。</p><p className="typed">分析对象可能不是照片。</p></div><button className="action locked"><LockKeyhole/> 后续档案正在封存</button><button className="restart" onClick={()=>{setStage('boot');setIndex(0);setAnswers([]);setNoticed(0)}}>清除本次观察记录</button></section>}
</main>}
