'use client';
import { useMemo, useState } from 'react';
import { ArrowLeft, Copy, Fingerprint, RotateCcw, Volume2, VolumeX } from 'lucide-react';
type Gender='men'|'women'; type Profile={alias:string;group:string;motive:string;scene:string;danger:number};
const asset=(name:string)=>`${import.meta.env.BASE_URL}${name}`;
const questions=[
{code:'社会切片 01',scene:'你掌握了足以摧毁同事声誉的私人证据。',detail:'他刚刚挡住了你的晋升，但仍然完全信任你。',options:[{text:'交给关键的人，让舆论替我动手',point:'E',sin:'envy'},{text:'继续潜伏，在最致命时刻使用',point:'I',sin:'wrath'}]},
{code:'社会切片 02',scene:'一个封闭团体正逐渐把你奉为精神核心。',detail:'他们愿意交出判断权，只换取你的认可。',options:[{text:'建立规则，让服从变得可测量',point:'S',sin:'pride'},{text:'创造一套无法证伪的信仰',point:'N',sin:'lust'}]},
{code:'社会切片 03',scene:'一场危机能换来你最想要的实验数据。',detail:'只要保持沉默，损失就会落在一群陌生人身上。',options:[{text:'记录变量，损失只是必要成本',point:'T',sin:'sloth'},{text:'操控情绪，让他们主动承担',point:'F',sin:'greed'}]},
{code:'社会切片 04',scene:'你接管了一个濒临崩溃的组织。',detail:'所有人都在等待你重建秩序。',options:[{text:'制定制度，清除不合格者',point:'J',sin:'pride'},{text:'制造混乱，在失控中攫取利益',point:'P',sin:'greed'}]},
{code:'社会切片 05',scene:'你发现一个人开始产生独立意志。',detail:'他曾经依赖你，如今却准备脱离控制。',options:[{text:'动员共同关系，让所有人孤立他',point:'E',sin:'envy'},{text:'让他相信离开我就无法生存',point:'I',sin:'lust'}]},
{code:'社会切片 06',scene:'你需要彻底摧毁一个人的自我。',detail:'没有摄像头，也不会留下直接证据。',options:[{text:'从金钱和日常习惯逐层剥夺',point:'S',sin:'greed'},{text:'重写信念，让他主动否定自己',point:'N',sin:'pride'}]},
{code:'社会切片 07',scene:'有人在公开场合揭穿了你的谎言。',detail:'人群尚未决定应该相信谁。',options:[{text:'拆解证词，用事实漏洞反杀',point:'T',sin:'wrath'},{text:'扮演受害者，让质疑者承受愧疚',point:'F',sin:'envy'}]},
{code:'社会切片 08',scene:'你已经得到想要的一切，却开始感到无聊。',detail:'眼前还有一群毫无防备的人。',options:[{text:'长期控制，让他们持续产出价值',point:'J',sin:'gluttony'},{text:'发起危险游戏，只为获得刺激',point:'P',sin:'gluttony'}]}];
const sins:Record<string,{name:string;latin:string;core:string}>={pride:{name:'傲慢',latin:'SUPERBIA',core:'你真正渴望的不是胜利，而是证明自己拥有定义他人价值的资格。'},greed:{name:'贪婪',latin:'AVARITIA',core:'你将一切关系折算为可占有的资源，得到之后仍会继续索取。'},lust:{name:'色欲',latin:'LUXURIA',core:'这里的欲不是情色，而是对亲密、崇拜与控制感永不满足的吞噬。'},envy:{name:'嫉妒',latin:'INVIDIA',core:'你无法容忍别人拥有你缺失的东西，于是更愿意毁掉它。'},gluttony:{name:'暴食',latin:'GULA',core:'刺激一旦出现就必须不断加码，直到他人的痛苦也只是消费品。'},wrath:{name:'暴怒',latin:'IRA',core:'你把伤害解释为清算，让复仇披上公平与正义的外衣。'},sloth:{name:'懒惰',latin:'ACEDIA',core:'你最大的恶来自拒绝承担责任：只要不亲自动手，灾难仿佛与你无关。'}};
const profiles:Record<string,Profile>={
INTJ:{alias:'社会达尔文屠夫',group:'理性极化 · NT',motive:'极致功利主义。将人视为可替换的低效零件，以“系统优化”为名实施冷酷清除。',scene:'惨白无影灯下，西装笔挺，手中把玩解剖刀；注视人的眼神像在评估无机物。',danger:96},
INTP:{alias:'无底线观测者',group:'理性极化 · NT',motive:'绝对求知欲。为了获得数据，旁观甚至促成灾难，对个体痛苦彻底脱敏。',scene:'粗糙监控画面里，暗室堆满屏幕；残酷社会实验正在播放，记录者平静敲下偏差值。',danger:94},
ENTJ:{alias:'马基雅维利暴君',group:'理性极化 · NT',motive:'绝对控制狂。把他人物化为目标燃料，用精密手段榨干其最后一丝社会价值。',scene:'仰视镜头中，人物立于落地窗前俯瞰城市；脚边散落破产清算书与死亡报道。',danger:99},
ENTP:{alias:'虚无主义煽动家',group:'理性极化 · NT',motive:'智力傲慢与反社会冲动。摧毁信仰、挑起动乱，只为完成一场自娱的思维游戏。',scene:'摇晃的手持 DV 拍到暴乱边缘的冷笑；塑料面具下，扩音器循环播放煽动频段。',danger:98},
INFJ:{alias:'精神邪教主',group:'理想极化 · NF',motive:'伪神救世主情结。利用共情精准撕裂心理防线，建立彻底的精神依附。',scene:'失真的录像带里，白衬衫布道者坐在信徒中央；温柔神情下是绝对控制欲。',danger:97},
INFP:{alias:'受害者暴君',group:'理想极化 · NF',motive:'畸形道德洁癖。将脆弱武器化，以舆论、愧疚和自毁威胁勒索他人。',scene:'逼仄卧室遍布揉碎的日记与药瓶；无辜泪眼直视监控，画外的人已被愧疚压垮。',danger:91},
ENFJ:{alias:'认知寄生母体',group:'理想极化 · NF',motive:'窒息的“大爱”控制。以拯救之名进行情感勒索，剥夺目标的独立意志。',scene:'闪光灯直射的家庭合影里，完美笑容近似假面；钳住肩膀的双手令身边人失去焦点。',danger:96},
ENFP:{alias:'狂热毒源体',group:'理想极化 · NF',motive:'灾难性的情绪剥削。用虚假热情卷入他人，吸干情绪价值后在崩溃前抽身。',scene:'高饱和派对抓拍中，鲜艳油彩覆盖面孔；满地狼藉与失控人群成为笑声背景。',danger:93},
ISTJ:{alias:'极权执行官',group:'秩序极化 · SJ',motive:'平庸之恶。放弃个人道德判断，成为残酷规则最精确、最稳定的执行齿轮。',scene:'黑白监控里，监狱般规整的办公室中，一枚红色合格章落向成排处置名单。',danger:92},
ISFJ:{alias:'窒息施恩者',group:'秩序极化 · SJ',motive:'病态依恋。制造危机、弱化他人，以维持“只有我能照顾你”的依赖关系。',scene:'泛黄宝丽来里，病床前的人端着一碗热汤；慈祥笑容与浓重消毒水味同时逼近。',danger:90},
ESTJ:{alias:'齿轮独裁者',group:'秩序极化 · SJ',motive:'微观极权。建立无法完成的连坐规则与考核，把系统性压迫视作天然秩序。',scene:'电梯监控死角里，领带勒得极紧；皮鞋缓慢碾过一份求职简历。',danger:95},
ESFJ:{alias:'蜂巢审判长',group:'秩序极化 · SJ',motive:'群氓暴政。操控社交圈、谣言与从众心理，完成不见血的社会性抹杀。',scene:'手机偷拍画面中，被簇拥的人指向镜头外低语；周围面孔浮现一致的排斥冷笑。',danger:93},
ISTP:{alias:'冰冷解剖者',group:'本能极化 · SP',motive:'机械破坏欲。把人视作可拆解结构，通过物理或心理拆解测试“机器”的极限。',scene:'密室角落的红外夜视中，面罩遮住表情；工具在实验台旁被逐件摆放整齐。',danger:98},
ISFP:{alias:'绝望美学家',group:'本能极化 · SP',motive:'死亡浪漫化。将悲剧与痛苦奉为艺术，为完成“杰作”诱导他人走向毁灭。',scene:'废弃画室布满暗红颜料；背对镜头的身影正在墙上完成一幅眩晕的抽象画。',danger:95},
ESTP:{alias:'掠食资本家',group:'本能极化 · SP',motive:'冲动掠夺。为刺激和利益无底线欺诈、敲诈，把摧毁人生视为成功狩猎。',scene:'地下钱庄监控中，浮夸人物抛起骗来的婚戒；脚边散落签满名字的借款合同。',danger:99},
ESFP:{alias:'痛觉狂欢客',group:'本能极化 · SP',motive:'病态感官暴政。将剥削、玩弄与制造悲剧当作对抗无聊的终极娱乐。',scene:'鱼眼镜头扭曲事故现场；人物对镜头天真大笑，把别人的灾难变成自拍背景。',danger:97}};
export default function Home(){
const[stage,setStage]=useState<'intro'|'test'|'result'>('intro');const[gender,setGender]=useState<Gender>('women');const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<string[]>([]);const[muted,setMuted]=useState(false);const[copied,setCopied]=useState(false);
const result=useMemo(()=>{const c=(x:string)=>answers.filter(a=>a.startsWith(x+':')).length;return`${c('E')>c('I')?'E':'I'}${c('S')>c('N')?'S':'N'}${c('T')>c('F')?'T':'F'}${c('J')>c('P')?'J':'P'}`},[answers]);
const sinKey=useMemo(()=>{const tally:Record<string,number>={};answers.forEach(a=>{const key=a.split(':')[1];tally[key]=(tally[key]||0)+1});return Object.entries(tally).sort((a,b)=>b[1]-a[1])[0]?.[0]||'pride'},[answers]);
const choose=(point:string,sin:string)=>{const next=[...answers,`${point}:${sin}`];setAnswers(next);index===7?setStage('result'):setIndex(index+1)};const restart=()=>{setStage('intro');setIndex(0);setAnswers([]);setCopied(false)};const copyResult=async()=>{const p=profiles[result],s=sins[sinKey];await navigator.clipboard?.writeText(`我的极恶人格侧写：${result}「${p.alias}」× 七宗罪「${s.name}」\n${s.core}\n#16型极恶人格 #七宗罪`);setCopied(true);setTimeout(()=>setCopied(false),1600)};
return <main className="game-shell"><div className="noise"/><header className="topbar"><div className="brand"><Fingerprint size={18}/><span>16 / 极恶人格侧写</span></div><button className="icon-btn" onClick={()=>setMuted(!muted)} aria-label={muted?'打开声音':'静音'}>{muted?<VolumeX/>:<Volume2/>}</button></header>
{stage==='intro'&&<section className="intro panel-enter"><div className="case-label">CASE NO. 016 · SEVEN SINS UNIT</div><h1>人格决定手段<br/><em>罪性决定欲望</em></h1><p className="lede">无鬼怪，无诅咒。<br/>只有剥削、操控，以及被合理化的七种欲望。</p><div className="evidence-grid"><button className={`evidence ${gender==='women'?'selected':''}`} onClick={()=>setGender('women')}><img src={asset('mbti-women.jpg')} alt="女性人格侧写"/><span>女性档案</span></button><button className={`evidence ${gender==='men'?'selected':''}`} onClick={()=>setGender('men')}><img src={asset('mbti-men.jpg')} alt="男性人格侧写"/><span>男性档案</span></button></div><button className="primary" onClick={()=>setStage('test')}>进入七罪侧写 <span>→</span></button><p className="micro">16 型人格 × 7 种罪性 · 虚构娱乐创作 · 不构成临床诊断</p></section>}
{stage==='test'&&<section className="test panel-enter" key={index}><div className="progress-row"><button className="back" onClick={()=>index?(setIndex(index-1),setAnswers(answers.slice(0,-1))):setStage('intro')}><ArrowLeft size={17}/> 撤回</button><span>{String(index+1).padStart(2,'0')} / 08</span></div><div className="progress"><i style={{width:`${((index+1)/8)*100}%`}}/></div><div className="timecode">REC ● {questions[index].code}</div><h2>{questions[index].scene}</h2><p className="scene-detail">{questions[index].detail}</p><div className="choices">{questions[index].options.map((o,i)=><button key={o.point} onClick={()=>choose(o.point,o.sin)}><b>0{i+1}</b><span>{o.text}</span><i>选择</i></button>)}</div><p className="warning">请选择更接近你“会如何作恶”的答案，而不是更正确的答案</p></section>}
{stage==='result'&&(()=>{const p=profiles[result],s=sins[sinKey];return <section className="result panel-enter"><div className="classified">七罪侧写完成 · RESTRICTED</div><div className="result-card"><div className="photo-wrap"><img src={asset(gender==='women'?'mbti-women.jpg':'mbti-men.jpg')} alt={`${result} 人格群像档案`}/><div className="scanline"/><span className="stamp">{s.name}</span></div><div className="result-copy"><p>{p.group}</p><h2>{result}</h2><h3>「{p.alias}」</h3></div><div className="risk"><span>社会危害指数</span><b>{p.danger}%</b><i><em style={{width:`${p.danger}%`}}/></i></div><div className="sin-seal"><small>主导罪性 · {s.latin}</small><strong>{s.name}</strong><p>{s.core}</p></div><h4 className="profile-label">核心恶意驱动</h4><p className="verdict">{p.motive}</p><h4 className="profile-label">犯罪现场影像</h4><blockquote>{p.scene}</blockquote><div className="tags"><span>七宗罪</span><span>行为极化</span><span>非临床诊断</span></div></div><button className="primary share" onClick={copyResult}><Copy size={18}/>{copied?'侧写已复制':'复制我的七罪侧写'}</button><button className="secondary" onClick={restart}><RotateCcw size={16}/> 重新接受评估</button><p className="micro">本测试为暗黑人格创作，不代表真实 MBTI 或心理疾病</p></section>})()}</main>}
